### ISSUE TITLE
Delay between hitting escape and entering command mode

### ISSUE THREAD

**Issue by adb-luna** [injinj/linecook#4]
While in insert mode, I am used to hitting escape and immediately being able to press k to go back in history. With linecook, I have to wait before k will be seen as a navigation key. I expect that linecook is queuing up the escape in case it is an encoded key of some kind. Is there a way to control that delay? I would like it to be 0.

**Comment by injinj** [comment]
I think the tcsetattr() controls that:  https://github.com/injinj/linecook/blob/b4d65895dc29c8e030fe683110af74f6dda6aa5b/src/ttycook.cpp#L1172

It's set VMIN = 1, VTIME = 0, which should be no delay.

What terminal are you using?

**Comment by adb-luna** [comment]
Thanks for the info, @injinj. The settings were already as you say.

Good question about the terminal, though. I tried some different scenarios, and I am seeing problem when running screen in GNOME Terminal and in Terminator. Without screen in the same terminal programs, no delay is required. I do not have any problems with bash (readline) in screen, though. Strange. In screen, TERM is set to screen-256color.

**Comment by injinj** [comment]
I'll see what bash is doing to tcgetattr, thanks for the setup info.

**Comment by injinj** [comment]
Screen has a default input char timeout of 300ms.  I can change that to 3ms with: (ctrl-a):maptimeout 3
This is a common problem with screen + vim:  https://vim.fandom.com/wiki/GNU_Screen_integration

**Comment by adb-luna** [comment]
Thanks for the info @injinj. Yes, changing maptimeout fixed it. I suspect I am not seeing this problem with bash because it does not interpret <Esc>k as anything except go-to-command-mode followed by k. linecook has a mapping of <Esc>k (META_K) to ACTION_SHOW_PREV_PAGE in EVILS mode.

Makes sense now. Thanks for looking into it!
